blank_issues_enabled: false
contact_links:
    - name: Ask a question
      url: https://github.com/red-explosion/laravel-sqids/discussions/new?category=q-a
      about: Ask the community for help
    - name: Request a feature
      url: https://github.com/red-explosion/laravel-sqids/discussions/new?category=ideas
      about: Share ideas for new features
